### ISSUE TITLE
Monitoring endpoint: Receive the time frame in input

### ISSUE THREAD

**Issue by aidin36** [octopus-sensing/octopus-sensing#41]
The `MonitoringEndpoint` sends back three seconds of data on each `GET` request. We want to extend it to receive the time frame as a parameter.

The use case is when an external software wants to receive online data (to process or monitor).

Also, it's a good idea to rename it to `RealtimeDataEndpoint`.

- The parameter should have a default of three seconds to be backward compatible.
- The parameter should have an upper limit. Sending big data between processes and over the network can be a lot of processing work which might affect the data collection. I recommend a maximum of 15 seconds of data.
- Need to keep the old name too, to keep the backwards compatibility. (i.e. by doing `import RealtimeDataEndpoint as MonitoringEndpoint`).
- And need to update the documents as well.

**Comment by nastaran62** [comment]
MonitoringEndpoint was renamed to RealtimeDataEndpoint and the time frame has been added as a duration parameter.
