### ISSUE TITLE
$ pip install octopus-sensing-visualizer

### ISSUE THREAD

**Issue by HaowenWeiJohn** [octopus-sensing/octopus-sensing#70]
Collecting sklearn (from neurokit<0.3.0,>=0.2.0->octopus-sensing-visualizer)
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

Hi, we got this issue when we install the `octopus-sensing-visualizer`

**Comment by aidin36** [comment]
Thanks for reporting this!

Visualizer uses an old package, `neurokit`. It hadn't been updated in the last three years. It depends on `sklearn`, and `sklearn` is now deprecated.
That's the source of the issue.

We need to update the code and move away from the old `neurokit`.

**Comment by aidin36** [comment]
I published a new version of `octopus-sensing-visualizer` with up-to-date dependencies. It fixes the issue.
Thanks for reporting this again! And sorry for the inconvenience.
